import { N, type NoteFreq } from './notes';

export type NoteStep = {
  n: NoteFreq;
  /** Duração em semicolcheias (16th notes: 1 = rápida, 2 = colcheia, 4 = semínima, 8 = mínima) */
  d: number;
  /** Volume relativo de 0 a 1 (padrão 0.8) */
  v?: number;
};

export type DrumStep = '.' | 'k' | 's' | 't' | 'p' | 'a'; // k=kick, s=snare, t=triangulo, p=pandeiro, a=alfaia

export type MusicTrack = {
  id: string;
  name: string;
  subtitle: string;
  genre: string;
  bpm: number;
  /** Ausente ou true: a fase fica em loop. false = jingle de uma vez. */
  loop?: boolean;
  lead: readonly NoteStep[];
  bass: readonly NoteStep[];
  arp?: readonly NoteStep[];
  drums: readonly DrumStep[];
};

export const TRACKS: Record<string, MusicTrack> = {
  title: {
    id: 'title',
    name: 'Tema dos Heróis',
    subtitle: 'Ana & Junior',
    genre: 'Pop Chiptune Acolhedor (118 BPM)',
    bpm: 118,
    lead: [
      // Frase A (C - G - Am - F)
      { n: N.E5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.C5, d: 4 },
      { n: N.D5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.D5, d: 4 },
      { n: N.C5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.A4, d: 4 },
      { n: N.G4, d: 2 },
      { n: N.A4, d: 2 },
      { n: N.C5, d: 4 },
      // Frase B
      { n: N.E5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.C6, d: 4 },
      { n: N.B5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.G5, d: 4 },
      { n: N.A5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.D5, d: 2 },
      { n: N.C5, d: 8 },
    ],
    bass: [
      { n: N.C3, d: 4 },
      { n: N.G3, d: 4 },
      { n: N.G2, d: 4 },
      { n: N.D3, d: 4 },
      { n: N.A2, d: 4 },
      { n: N.E3, d: 4 },
      { n: N.F2, d: 4 },
      { n: N.C3, d: 4 },
      { n: N.C3, d: 4 },
      { n: N.G3, d: 4 },
      { n: N.G2, d: 4 },
      { n: N.D3, d: 4 },
      { n: N.F2, d: 4 },
      { n: N.G2, d: 4 },
      { n: N.C3, d: 8 },
    ],
    arp: [
      { n: N.C4, d: 1 },
      { n: N.E4, d: 1 },
      { n: N.G4, d: 1 },
      { n: N.C5, d: 1 },
      { n: N.G3, d: 1 },
      { n: N.B3, d: 1 },
      { n: N.D4, d: 1 },
      { n: N.G4, d: 1 },
      { n: N.A3, d: 1 },
      { n: N.C4, d: 1 },
      { n: N.E4, d: 1 },
      { n: N.A4, d: 1 },
      { n: N.F3, d: 1 },
      { n: N.A3, d: 1 },
      { n: N.C4, d: 1 },
      { n: N.F4, d: 1 },
      { n: N.C4, d: 1 },
      { n: N.E4, d: 1 },
      { n: N.G4, d: 1 },
      { n: N.C5, d: 1 },
      { n: N.G3, d: 1 },
      { n: N.B3, d: 1 },
      { n: N.D4, d: 1 },
      { n: N.G4, d: 1 },
      { n: N.F3, d: 1 },
      { n: N.A3, d: 1 },
      { n: N.G3, d: 1 },
      { n: N.B3, d: 1 },
      { n: N.C4, d: 8 },
    ],
    drums: [
      'k', '.', 't', '.', 's', '.', 't', '.',
      'k', '.', 't', 'k', 's', '.', 't', '.',
      'k', '.', 't', '.', 's', '.', 't', '.',
      'k', '.', 't', 'k', 's', '.', 't', '.',
      'k', '.', 't', '.', 's', '.', 't', '.',
      'k', '.', 't', 'k', 's', '.', 't', '.',
      'k', 'k', 't', '.', 's', '.', 's', '.',
      'k', '.', '.', '.', '.', '.', '.', '.',
    ],
  },

  quintal: {
    id: 'quintal',
    name: 'Quintal da Escola',
    subtitle: 'Fase 1-1 · Adição',
    genre: 'Choro Infantil Alegre (122 BPM)',
    bpm: 122,
    lead: [
      // Melodia saltitante com arpejos de choro em G Maior
      { n: N.D5, d: 1 },
      { n: N.G5, d: 2 },
      { n: N.B5, d: 2 },
      { n: N.A5, d: 1 },
      { n: N.G5, d: 2 },
      { n: N.Fs5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.E5, d: 4 },
      { n: N.C5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.D5, d: 4 },
      { n: N.B4, d: 2 },
      { n: N.D5, d: 2 },
      { n: N.A4, d: 6 },
      { n: N._, d: 2 },

      { n: N.D5, d: 1 },
      { n: N.G5, d: 2 },
      { n: N.B5, d: 2 },
      { n: N.A5, d: 1 },
      { n: N.G5, d: 2 },
      { n: N.B5, d: 2 },
      { n: N.D6, d: 4 },
      { n: N.C6, d: 2 },
      { n: N.B5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.Fs5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.G5, d: 6 },
      { n: N._, d: 2 },
    ],
    bass: [
      // Baixaria sincopada de choro
      { n: N.G2, d: 3 },
      { n: N.D3, d: 1 },
      { n: N.B2, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.C3, d: 3 },
      { n: N.G3, d: 1 },
      { n: N.E3, d: 2 },
      { n: N.G3, d: 2 },
      { n: N.D3, d: 3 },
      { n: N.A3, d: 1 },
      { n: N.Fs3, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.G2, d: 2 },
      { n: N.B2, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.Fs3, d: 2 },

      { n: N.G2, d: 3 },
      { n: N.D3, d: 1 },
      { n: N.B2, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.C3, d: 3 },
      { n: N.E3, d: 1 },
      { n: N.G3, d: 2 },
      { n: N.E3, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.Fs3, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.G2, d: 6 },
      { n: N._, d: 2 },
    ],
    drums: [
      'p', 't', 'p', 'p', 's', 't', 'p', 't',
      'p', 't', 'p', 'p', 's', 't', 'p', 't',
      'p', 't', 'p', 'p', 's', 't', 'p', 't',
      'p', 't', 'p', 'p', 's', 'p', 's', 't',
      'p', 't', 'p', 'p', 's', 't', 'p', 't',
      'p', 't', 'p', 'p', 's', 't', 'p', 't',
      'p', 't', 'p', 'p', 's', 't', 'p', 't',
      'p', 'p', 's', 'p', 'k', '.', '.', '.',
    ],
  },

  feira: {
    id: 'feira',
    name: 'Feira do Bairro',
    subtitle: 'Fase 1-2 · Saci-Pererê',
    genre: 'Samba / Gafieira Sincopado (130 BPM)',
    bpm: 130,
    lead: [
      // Melodia malandra em Ré menor / Fá Maior
      { n: N.A4, d: 1 },
      { n: N.D5, d: 2 },
      { n: N.F5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.D5, d: 1 },
      { n: N.Cs5, d: 2 },
      { n: N.D5, d: 2 },
      { n: N.E5, d: 4 },
      { n: N.A4, d: 2 },
      { n: N.Cs5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.F5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.D5, d: 4 },

      { n: N.F5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.A5, d: 4 },
      { n: N.G5, d: 2 },
      { n: N.F5, d: 2 },
      { n: N.E5, d: 4 },
      { n: N.D5, d: 2 },
      { n: N.F5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.Cs5, d: 2 },
      { n: N.D5, d: 6 },
      { n: N._, d: 2 },
    ],
    bass: [
      // Levada de Samba: tum ... dum-dum
      { n: N.D3, d: 3 },
      { n: N.A2, d: 1 },
      { n: N._, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.A2, d: 3 },
      { n: N.E3, d: 1 },
      { n: N._, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.A2, d: 3 },
      { n: N.Cs3, d: 1 },
      { n: N._, d: 2 },
      { n: N.E3, d: 2 },
      { n: N.D3, d: 3 },
      { n: N.A2, d: 1 },
      { n: N._, d: 2 },
      { n: N.D3, d: 2 },

      { n: N.F2, d: 3 },
      { n: N.C3, d: 1 },
      { n: N._, d: 2 },
      { n: N.F2, d: 2 },
      { n: N.C3, d: 3 },
      { n: N.G2, d: 1 },
      { n: N._, d: 2 },
      { n: N.C3, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.Cs3, d: 2 },
      { n: N.E3, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.D3, d: 6 },
      { n: N._, d: 2 },
    ],
    drums: [
      'p', '.', 't', 'p', 's', '.', 'p', 't',
      'p', '.', 't', 'p', 's', 'p', 't', '.',
      'p', '.', 't', 'p', 's', '.', 'p', 't',
      'p', '.', 't', 'p', 's', 'p', 's', 't',
      'p', '.', 't', 'p', 's', '.', 'p', 't',
      'p', '.', 't', 'p', 's', 'p', 't', '.',
      'p', 't', 'p', 't', 's', 'p', 's', 'p',
      'k', '.', '.', '.', '.', '.', '.', '.',
    ],
  },

  festa: {
    id: 'festa',
    name: 'Festa Junina no Pátio',
    subtitle: 'Fase 1-3 · Boitatá & Boto',
    genre: 'Forró Pé-de-Serra / Baião 16-bit (136 BPM)',
    bpm: 136,
    lead: [
      // Sanfona em Lá Menor / Dó Maior
      { n: N.A4, d: 2 },
      { n: N.C5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.D5, d: 2 },
      { n: N.C5, d: 2 },
      { n: N.D5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.D5, d: 2 },
      { n: N.C5, d: 2 },
      { n: N.A4, d: 4 },
      { n: N.E4, d: 4 },

      { n: N.C5, d: 2 },
      { n: N.D5, d: 2 },
      { n: N.E5, d: 4 },
      { n: N.G5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.G5, d: 4 },
      { n: N.E5, d: 2 },
      { n: N.D5, d: 2 },
      { n: N.C5, d: 2 },
      { n: N.B4, d: 2 },
      { n: N.A4, d: 6 },
      { n: N._, d: 2 },
    ],
    bass: [
      // Zabumba grave no contratempo (Tum... tá-tá)
      { n: N.A2, d: 3 },
      { n: N.E3, d: 1 },
      { n: N.A2, d: 2 },
      { n: N.E3, d: 2 },
      { n: N.G2, d: 3 },
      { n: N.D3, d: 1 },
      { n: N.G2, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.F2, d: 3 },
      { n: N.C3, d: 1 },
      { n: N.F2, d: 2 },
      { n: N.C3, d: 2 },
      { n: N.E2, d: 4 },
      { n: N.E3, d: 4 },

      { n: N.C3, d: 3 },
      { n: N.G3, d: 1 },
      { n: N.C3, d: 2 },
      { n: N.G3, d: 2 },
      { n: N.G2, d: 3 },
      { n: N.D3, d: 1 },
      { n: N.G2, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.E2, d: 2 },
      { n: N.Gs2, d: 2 },
      { n: N.B2, d: 2 },
      { n: N.E3, d: 2 },
      { n: N.A2, d: 6 },
      { n: N._, d: 2 },
    ],
    arp: [
      // Arpejo de triângulo e sanfona
      { n: N.A4, d: 1 },
      { n: N.C5, d: 1 },
      { n: N.E5, d: 1 },
      { n: N.A5, d: 1 },
      { n: N.G4, d: 1 },
      { n: N.B4, d: 1 },
      { n: N.D5, d: 1 },
      { n: N.G5, d: 1 },
      { n: N.F4, d: 1 },
      { n: N.A4, d: 1 },
      { n: N.C5, d: 1 },
      { n: N.F5, d: 1 },
      { n: N.E4, d: 1 },
      { n: N.Gs4, d: 1 },
      { n: N.B4, d: 1 },
      { n: N.E5, d: 1 },
    ],
    drums: [
      // Batida autêntica de Baião (k . . k s . t .)
      'k', '.', '.', 'k', 's', '.', 't', '.',
      'k', '.', '.', 'k', 's', '.', 't', '.',
      'k', '.', '.', 'k', 's', '.', 't', '.',
      'k', '.', '.', 'k', 's', '.', 't', '.',
      'k', '.', '.', 'k', 's', '.', 't', '.',
      'k', '.', '.', 'k', 's', '.', 't', '.',
      'k', '.', '.', 'k', 's', '.', 't', '.',
      'k', 'k', 's', 's', 'k', '.', '.', '.',
    ],
  },

  sertao: {
    id: 'sertao',
    name: 'Travessia do Sertão',
    subtitle: 'Fase 1-4 · Ventania & Caatinga',
    genre: 'Maracatu Épico & Galope Chiptune (142 BPM)',
    bpm: 142,
    lead: [
      // Vento e determinação em Mi Menor
      { n: N.E5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.Fs5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.D5, d: 2 },
      { n: N.B4, d: 4 },
      { n: N.D5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.B5, d: 4 },
      { n: N.A5, d: 4 },

      { n: N.B5, d: 2 },
      { n: N.D6, d: 2 },
      { n: N.B5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.Fs5, d: 2 },
      { n: N.E5, d: 4 },
      { n: N.Fs5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.Fs5, d: 2 },
      { n: N.Ds5, d: 2 },
      { n: N.E5, d: 6 },
      { n: N._, d: 2 },
    ],
    bass: [
      // Batida de Maracatu pesada (Alfaias)
      { n: N.E2, d: 2 },
      { n: N.E2, d: 2 },
      { n: N._, d: 1 },
      { n: N.E2, d: 3 },
      { n: N.B2, d: 2 },
      { n: N.D3, d: 2 },
      { n: N._, d: 1 },
      { n: N.B2, d: 3 },
      { n: N.C3, d: 2 },
      { n: N.C3, d: 2 },
      { n: N._, d: 1 },
      { n: N.C3, d: 3 },
      { n: N.D3, d: 2 },
      { n: N.B2, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.B2, d: 2 },

      { n: N.G2, d: 2 },
      { n: N.G2, d: 2 },
      { n: N._, d: 1 },
      { n: N.G2, d: 3 },
      { n: N.A2, d: 2 },
      { n: N.A2, d: 2 },
      { n: N._, d: 1 },
      { n: N.A2, d: 3 },
      { n: N.B2, d: 2 },
      { n: N.Ds3, d: 2 },
      { n: N.Fs3, d: 2 },
      { n: N.B2, d: 2 },
      { n: N.E2, d: 6 },
      { n: N._, d: 2 },
    ],
    drums: [
      // Alfaia de Maracatu (a = alfaia pesada)
      'a', 'a', '.', 'a', 's', '.', 'a', '.',
      'a', 'a', '.', 'a', 's', 'a', 's', '.',
      'a', 'a', '.', 'a', 's', '.', 'a', '.',
      'a', 'a', '.', 'a', 's', 'a', 's', 'a',
      'a', 'a', '.', 'a', 's', '.', 'a', '.',
      'a', 'a', '.', 'a', 's', 'a', 's', '.',
      'a', 'a', 's', 'a', 'a', 'a', 's', 'a',
      'a', '.', '.', '.', '.', '.', '.', '.',
    ],
  },

  mata: {
    id: 'mata',
    name: 'Mata do Curupira',
    subtitle: 'Fase 1-5 · Chefe do Mundo 1',
    genre: 'Carimbó & Boss Fight Tribal (152 BPM)',
    bpm: 152,
    lead: [
      // Tema rápido e urgente em Ré Menor
      { n: N.D5, d: 1 },
      { n: N.F5, d: 1 },
      { n: N.A5, d: 2 },
      { n: N.D6, d: 2 },
      { n: N.Cs6, d: 2 },
      { n: N.D6, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.F5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.Bb4, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.F5, d: 2 },
      { n: N.E5, d: 4 },

      { n: N.F5, d: 2 },
      { n: N.G5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.D6, d: 2 },
      { n: N.C6, d: 2 },
      { n: N.Bb4, d: 2 },
      { n: N.A5, d: 4 },
      { n: N.G5, d: 2 },
      { n: N.F5, d: 2 },
      { n: N.E5, d: 2 },
      { n: N.Cs5, d: 2 },
      { n: N.D5, d: 6 },
      { n: N._, d: 2 },
    ],
    bass: [
      // Curimbó rápido em semicocheia
      { n: N.D3, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.D3, d: 1 },
      { n: N.D3, d: 1 },
      { n: N.A2, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.D3, d: 1 },
      { n: N.D3, d: 1 },
      { n: N.A2, d: 2 },
      { n: N.G2, d: 2 },
      { n: N.D3, d: 2 },
      { n: N.G2, d: 1 },
      { n: N.G2, d: 1 },
      { n: N.D3, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.E3, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.Cs3, d: 2 },

      { n: N.Bb2, d: 2 },
      { n: N.F3, d: 2 },
      { n: N.Bb2, d: 2 },
      { n: N.F3, d: 2 },
      { n: N.C3, d: 2 },
      { n: N.G3, d: 2 },
      { n: N.C3, d: 2 },
      { n: N.G3, d: 2 },
      { n: N.A2, d: 2 },
      { n: N.Cs3, d: 2 },
      { n: N.E3, d: 2 },
      { n: N.A3, d: 2 },
      { n: N.D3, d: 6 },
      { n: N._, d: 2 },
    ],
    drums: [
      // Percussão tribal de Carimbó veloz
      'k', 't', 'k', 's', 'k', 't', 'k', 's',
      'k', 't', 'k', 's', 'k', 's', 'k', 's',
      'k', 't', 'k', 's', 'k', 't', 'k', 's',
      'k', 't', 'k', 's', 'k', 's', 'k', 's',
      'k', 't', 'k', 's', 'k', 't', 'k', 's',
      'k', 't', 'k', 's', 'k', 't', 'k', 's',
      'k', 'k', 's', 'k', 'k', 's', 's', 's',
      'k', '.', '.', '.', '.', '.', '.', '.',
    ],
  },

  victory: {
    id: 'victory',
    name: 'Vitória / Conquista',
    subtitle: 'Fim de Fase · 3 Estrelas',
    genre: 'Fanfarra Frevo & Celebração (140 BPM)',
    bpm: 140,
    loop: false,
    lead: [
      { n: N.C5, d: 1 },
      { n: N.E5, d: 1 },
      { n: N.G5, d: 1 },
      { n: N.C6, d: 3 },
      { n: N.G5, d: 2 },
      { n: N.A5, d: 2 },
      { n: N.B5, d: 2 },
      { n: N.C6, d: 6 },
      { n: N._, d: 2 },
    ],
    bass: [
      { n: N.C3, d: 2 },
      { n: N.E3, d: 2 },
      { n: N.G3, d: 2 },
      { n: N.C4, d: 2 },
      { n: N.F3, d: 2 },
      { n: N.G3, d: 2 },
      { n: N.C3, d: 6 },
      { n: N._, d: 2 },
    ],
    drums: [
      'k', 's', 'k', 's', 'k', 's', 'k', 's',
      'k', 'k', 's', 's', 'k', '.', '.', '.',
    ],
  },
};
